# Generated by Django 4.2.4 on 2023-11-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(help_text='from email', max_length=254)),
                ('to_email', models.EmailField(help_text='To email', max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
