# Generated by Django 4.2.4 on 2023-12-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
