# Generated by Django 4.2.4 on 2023-12-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Firstclass',
        ),
    ]
